version: 1.0.{build}

# Operating system (build VM template)
os: Windows Server 2012 R2

# scripts that are called at very beginning, before repo cloning
init:
#  - git config --global core.autocrlf input


# clone directory
clone_folder: c:\projects\DewritoLauncher

platform: x86
configuration: Release

install:
  # by default, all script lines are interpreted as batch

build:
  project: DoritoPatcher.sln      # path to Visual Studio solution or project

# scripts to run before build
before_build:


# scripts to run after build
after_build:


artifacts:
  - path: C:\projects\DewritoLauncher\DoritoPatcherWPF\bin\x86\Release\DoritoPatcherWPF.exe
    name: DewritoLauncher.exe

#deploy_script:
#  - cd c:\projects\sqlite
#  - curl -T sqlite.zip --user %ACCOUNT% https://webdav.yandex.ru/libs/sqlite.zip
